apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  namespace: seichi-minecraft
  name: bugsink-secret-credentials
spec:
  forceRegenerate: false
  fields:
    - fieldName: "secret_key"
      encoding: "hex"
      length: "50"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bugsink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugsink
  template:
    metadata:
      labels:
        app: bugsink
    spec:
      containers:
        - name: bugsink
          image: bugsink/bugsink:2.0.6
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bugsink-secret-credentials
                  key: secret_key
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bugsink-db-credentials
                  key: password
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bugsink-admin-password
                  key: ADMIN_PASSWORD
            - name: CREATE_SUPERUSER
              value: "admin:$(ADMIN_PASSWORD)"
            - name: PORT
              value: "9000"
            - name: DATABASE_URL
              value: mysql://bugsink:$(MYSQL_PASSWORD)@mariadb/bugsink
            - value: SINGLE_TEAM
              name: "True"
            - name: BEHIND_HTTPS_PROXY
              value: "True"
            - name: BASE_URL
              value: "https://bugsink-dsn.onp-k8s.admin.seichi.click"
            - name: ALLOWED_HOSTS
              value: "bugsink.onp-k8s.admin.seichi.click,bugsink-dsn.onp-k8s.admin.seichi.click,bugsink.seichi-minecraft"
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
              ephemeral-storage: 500Mi
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
