apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage-workflow-sa
  namespace: garage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garage-workflow-role
  namespace: garage
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garage-workflow-binding
  namespace: garage
subjects:
  - kind: ServiceAccount
    name: garage-workflow-sa
    namespace: garage
roleRef:
  kind: Role
  name: garage-workflow-role
  apiGroup: rbac.authorization.k8s.io
