apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seichi-debug-minecraft

resources:
  - "./service-monitor.yaml"
  - "./service.yaml"
  - "./stateful-set.yaml"
  - "./plugin-config.yaml"
  - "./ops-config.yaml"
  - "./multiverse-portals-config.yaml"
  - "./seichiassist-config.yaml"
  - "./seichiassist-downloader.yaml"
