apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  namespace: seichi-minecraft
  name: seichi-portal-rabbitmq-credentials
spec:
  forceRegenerate: false
  fields:
    - fieldName: "password"
      encoding: "hex"
      length: "32"
