apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parca-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: parca
    server: https://kubernetes.default.svc
  project: cluster-wide-apps
  source:
    repoURL: https://github.com/parca-dev/parca
    targetRevision: v0.25.0
    path: .
    directory:
      include: kubernetes-manifest.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parca-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  destination:
    namespace: parca
    server: https://kubernetes.default.svc
  project: cluster-wide-apps
  source:
    repoURL: https://github.com/parca-dev/parca-agent
    targetRevision: v0.45.0
    path: .
    directory:
      include: kubernetes-manifest.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true