apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seichi-debug-bungeesemaphore-valkey
  namespace: argocd
spec:
  project: seichi-debug-gateway
  source:
    chart: valkey
    repoURL: 'registry-1.docker.io/bitnamicharts'
    path: 'valkey'
    targetRevision: 5.0.13
    helm:
      releaseName: seichi-debug-bungeesemaphore-valkey
      values: |
        architecture: standalone
        auth:
          enabled: false
        commonConfiguration: |-
          notify-keyspace-events "Eg$x"
        primary:
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
          extraFlags:
            # https://github.com/GiganticMinecraft/seichi_infra/issues/468
            - "--maxmemory 2048mb"
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: prometheus
          prometheusRule:
            enabled: true
            additionalLabels:
              release: prometheus
            rules:
              - alert: ValkeyDown
                expr: valkey_up{service="{{ template "common.names.fullname" . }}-metrics"} == 0
                for: 2m
                labels:
                  severity: error
                annotations:
                  summary: Valkey&reg; instance {{ "{{ $labels.instance }}" }} down
                  description: Valkey&reg; instance {{ "{{ $labels.instance }}" }} is down
              - alert: ValkeyMemoryHigh
                expr: >
                  valkey_memory_used_bytes{service="{{ template "common.names.fullname" . }}-metrics"} * 100
                  /
                  valkey_memory_max_bytes{service="{{ template "common.names.fullname" . }}-metrics"}
                  > 90
                for: 2m
                labels:
                  severity: error
                annotations:
                  summary: Valkey&reg; instance {{ "{{ $labels.instance }}" }} is using too much memory
                  description: |
                    Valkey&reg; instance {{ "{{ $labels.instance }}" }} is using {{ "{{ $value }}" }}% of its available memory.
              - alert: ValkeyKeyEviction
                expr: |
                  increase(valkey_evicted_keys_total{service="{{ template "common.names.fullname" . }}-metrics"}[5m]) > 0
                for: 1s
                labels:
                  severity: error
                annotations:
                  summary: Valkey&reg; instance {{ "{{ $labels.instance }}" }} has evicted keys
                  description: |
                    Valkey&reg; instance {{ "{{ $labels.instance }}" }} has evicted {{ "{{ $value }}" }} keys in the last 5 minutes.
  destination:
    server: https://kubernetes.default.svc
    namespace: seichi-debug-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
