apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mcserver
    release: prometheus
    mcserver: debug-s2
  name: mcserver-metrics--debug-s2
spec:
  endpoints:
    - interval: 30s
      port: jmx-metrics
  selector:
    matchLabels:
      app: mcserver
      role: metrics
      mcserver: debug-s2
