apiVersion: v1
kind: ConfigMap
metadata:
  namespace: seichi-debug-minecraft
  name: debug-db-migrations
data:
  40-debug-server-migrations.sql: |
    USE seichiassist;
    UPDATE item_migration_in_server_world_levels SET server_id = 'deb-s1' WHERE server_id = 's1';
