apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: upload-world-to-minio-weekly
  namespace: seichi-debug-minecraft
  annotations:
    workflows.argoproj.io/description: "毎週月曜日 AM 1:00 (JST) にワールドデータをGarageにアップロード"
spec:
  schedule: "0 1 * * 1"
  timezone: "Asia/Tokyo"
  concurrencyPolicy: "Forbid"
  workflowSpec:
    workflowTemplateRef:
      name: upload-world-to-minio
