apiVersion: v1
kind: ServiceAccount
metadata:
  name: upload-world-to-minio-workflow-sa
  namespace: seichi-debug-minecraft
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: upload-world-to-minio-workflow-role
  namespace: seichi-debug-minecraft
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: upload-world-to-minio-workflow-binding
  namespace: seichi-debug-minecraft
subjects:
  - kind: ServiceAccount
    name: upload-world-to-minio-workflow-sa
    namespace: seichi-debug-minecraft
roleRef:
  kind: Role
  name: upload-world-to-minio-workflow-role
  apiGroup: rbac.authorization.k8s.io
