apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    repoURL: https://github.com/SynologyOpenSource/synology-csi.git
    path: deploy/kubernetes/v1.20
    targetRevision: v1.1.0
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: synology-csi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
